import './globals.css'
import { Inter } from 'next/font/google'
import NextAuthSessionProvider from './providers/sessionProvider'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import { GlobalContextProvider } from './context/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <GlobalContextProvider>
          <main className='bg-gray-100 '>
            <Sidebar>
              <Header/>
              {children}
            </Sidebar>
          </main>
          </GlobalContextProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
